project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "*.md"

website:
  title: "dashboard.v2"
  navbar:
    left:
      - href: index.qmd
        text: About This Project
      - href: demographics.qmd
        text: Demographics
      - href: datingquestions.qmd
        text: Dating Questions
      - href: descriptors.qmd
        text: Descriptors
      - href: map.qmd
        text: Map
      - href: datatable.qmd
        text: Data Table
      - href: test.qmd
        text: TEST


format:
  html:
    theme:
      - lumen
      - theme.scss
    css: styles.scss
    toc: true
    smooth-scroll: true

    include-in-header:
      text: |
        <link rel="stylesheet"
              href="https://cdn.jsdelivr.net/npm/glightbox/dist/css/glightbox.min.css">

        <script src="https://cdn.jsdelivr.net/npm/glightbox/dist/js/glightbox.min.js"></script>

        <script>
        document.addEventListener("DOMContentLoaded", function () {

          document.querySelectorAll(".cell-output-display img").forEach(function(img) {

            if (img.parentElement.tagName.toLowerCase() === "a") return;

            const link = document.createElement("a");
            link.href = img.src;
            link.className = "glightbox";

            img.parentNode.insertBefore(link, img);
            link.appendChild(img);

          });

          GLightbox();
        });
        </script>