project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "*.md"

website:
  title: "dashboard.v2"
  navbar:
    left:
      - href: index.qmd
        text: About This Project
      - href: demographics.qmd
        text: Demographics
      - href: datingquestions.qmd
        text: Dating Questions
      - href: descriptors.qmd
        text: Descriptors
      - href: map.qmd
        text: Map
      - href: datatable.qmd
        text: Data Table
      - href: test.qmd
        text: TEST


format:
  html:
    theme:
      - lumen
      - theme.scss
    css: styles.scss
    toc: true
    smooth-scroll: true