---
editor: visual

format:
  html:
    page-layout: full
    theme: theme.scss
    css: styles.scss
---

```{r}
#| include: false
source("setup.R")
```

::: {.callout-note title="Helpful Tips"}
You can hover your mouse above "About Me" column entries to read the full text associated with the profile. The formatting of this table is a work in progress.
:::

```{r, echo=FALSE}
stupiddftable <- stupiddf3 %>%
  select(-...1)
#change n/a to "no response" in character columns, not numeric
stupiddftable$MembershipType[is.na(stupiddftable$MembershipType)] <- "-"
stupiddftable$MaritalStatus[is.na(stupiddftable$MaritalStatus)] <- "-"
stupiddftable$WantChildren[is.na(stupiddftable$WantChildren)] <- "-"
stupiddftable$HaveChildren[is.na(stupiddftable$HaveChildren)] <- "-"
stupiddftable$City[is.na(stupiddftable$City)] <- "-"
stupiddftable$`State/Region`[is.na(stupiddftable$`State/Region`)] <- "-"
stupiddftable$Country[is.na(stupiddftable$Country)] <- "-"
stupiddftable$Country[is.na(stupiddftable$Country)] <- "-"
stupiddftable$AstrologicalSign[is.na(stupiddftable$AstrologicalSign)] <- "-"
stupiddftable$Zipcode[is.na(stupiddftable$Zipcode)] <- "-"
stupiddftable$AboutMe[is.na(stupiddftable$AboutMe)] <- "-"
stupiddftable$EducationLevel[is.na(stupiddftable$EducationLevel)] <- "-"
stupiddftable$Income[is.na(stupiddftable$Income)] <- "-"
stupiddftable$TestedIQ[is.na(stupiddftable$TestedIQ)] <- "-"
stupiddftable$MyersBriggs[is.na(stupiddftable$MyersBriggs)] <- "-"
stupiddftable$LookingFor[is.na(stupiddftable$LookingFor)] <- "-"
stupiddftable$PoliticalOrientaion[is.na(stupiddftable$PoliticalOrientaion)] <- "-"
stupiddftable$Diet[is.na(stupiddftable$Diet)] <- "-"
stupiddftable$Ancestry[is.na(stupiddftable$Ancestry)] <- "-"
stupiddftable$Race[is.na(stupiddftable$Race)] <- "-"
stupiddftable$HumanPhenotypes[is.na(stupiddftable$HumanPhenotypes)] <- "-"
stupiddftable$BodyType[is.na(stupiddftable$BodyType)] <- "-"
stupiddftable$Hair[is.na(stupiddftable$Hair)] <- "-"
stupiddftable$Height[is.na(stupiddftable$Height)] <- "-"
stupiddftable$EyeColor[is.na(stupiddftable$EyeColor)] <- "-"
stupiddftable$BestFeatures[is.na(stupiddftable$BestFeatures)] <- "-"
stupiddftable$Tattoos[is.na(stupiddftable$Tattoos)] <- "-"
stupiddftable$BloodType[is.na(stupiddftable$BloodType)] <- "-"
stupiddftable$Language[is.na(stupiddftable$Language)] <- "-"
stupiddftable$Interests[is.na(stupiddftable$Interests)] <- "-"
stupiddftable$StanceOnVaccination[is.na(stupiddftable$StanceOnVaccination)] <- "-"
stupiddftable$Polygyny[is.na(stupiddftable$Polygyny)] <- "-"
stupiddftable$Piercings[is.na(stupiddftable$Piercings)] <- "-"
stupiddftable$LookingForInPerson[is.na(stupiddftable$LookingForInPerson)] <- "-"
stupiddftable$Smoking[is.na(stupiddftable$Smoking)] <- "-"
stupiddftable$GeographicFlexibility[is.na(stupiddftable$GeographicFlexibility)] <- "-"
stupiddftable$FavoriteVacationSpot[is.na(stupiddftable$FavoriteVacationSpot)] <- "-"
stupiddftable$IdealFirstDate[is.na(stupiddftable$IdealFirstDate)] <- "-"
stupiddftable$HumanDesignType[is.na(stupiddftable$HumanDesignType)] <- "-"
stupiddftable$PassionateAbout[is.na(stupiddftable$PassionateAbout)] <- "-"
stupiddftable$Spirituality[is.na(stupiddftable$Spirituality)] <- "-"
stupiddftable$Mindset[is.na(stupiddftable$Mindset)] <- "-"
stupiddftable$Pets[is.na(stupiddftable$Pets)] <- "-"
stupiddftable$Accomodation[is.na(stupiddftable$Accomodation)] <- "-"
stupiddftable$Weight[is.na(stupiddftable$Weight)] <- "-"
stupiddftable$ChildrenLivesWith[is.na(stupiddftable$ChildrenLivesWith)] <- "-"
stupiddftable$Virginity[is.na(stupiddftable$Virginity)] <- "-"

#rename pseudonym displayed
stupiddftable <- stupiddftable %>% rename(Pseudonym_Displayed = 'Pseudonym Displayed')

```

```{r}
#| echo: false

reactable(
  stupiddftable,
  class = "my-table",
  resizable = TRUE,
  columns = list(

    MembershipType = colDef(name = "Membership Type"),
    Pseudonym_Displayed = colDef(name = "Pseudonym Displayed"),

    Seeking_a = colDef(name = "Seeking A"),
    MaritalStatus = colDef(name = "Marital Status"),
    WantChildren = colDef(name = "Wants Children"),
    HaveChildren = colDef(name = "Has Children"),

    AstrologicalSign = colDef(name = "Astrological Sign"),

    AboutMe = colDef(
      name = "About Me",
      cell = function(value) {
        if (is.na(value) || value == "") return("")
        tippy(value, tooltip = value)
      },
      style = list(
        whiteSpace = "nowrap",
        overflow = "hidden",
        textOverflow = "ellipsis"
      )
    ),

    EducationLevel = colDef(name = "Education Level"),
    TestedIQ = colDef(name = "I.Q. Score"),
    MyersBriggs = colDef(name = "Myers-Briggs Type"),
    LookingFor = colDef(name = "Looking For"),
    PoliticalOrientaion = colDef(name = "Political Orientation"),
    HumanPhenotypes = colDef(name = "Human Phenotypes"),
    BodyType = colDef(name = "Body Type"),
    EyeColor = colDef(name = "Eye Color"),
    BestFeatures = colDef(name = "Best Features"),
    BloodType = colDef(name = "Blood Type"),
    StanceOnVaccination = colDef(name = "Stance on Vaccination"),
    LookingForInPerson = colDef(name = "Looking for in a Person"),
    GeographicFlexibility = colDef(name = "Geographic Flexibility"),
    FavoriteVacationSpot = colDef(name = "Favorite Vacation Spot"),
    IdealFirstDate = colDef(name = "Ideal First Date"),
    HumanDesignType = colDef(name = "Human Design Type"),
    PassionateAbout = colDef(name = "Passionate About"),
    ChildrenLivesWith = colDef(name = "Lives with Children"),

    Activity = colDef(
      name = "Activity",
      cell = function(value) {
        if (is.na(value) || value == "") return("")
        tippy(value, tooltip = value)
      },
      style = list(
        whiteSpace = "nowrap",
        overflow = "hidden",
        textOverflow = "ellipsis"
      )
    ),

    Nickname = colDef(
      name = "Nickname",
      cell = JS('function(cellInfo) {
        const Pseudonym_Displayed = cellInfo.row["Pseudonym_Displayed"] || "Unknown"
        return `
          <div>
            <div style="font-weight: 600">${cellInfo.value}</div>
            <div style="font-size: 0.75rem; opacity: 0.7">${Pseudonym_Displayed}</div>
          </div>
        `
      }'),
      html = TRUE
    ),

    Pseudonym_Displayed = colDef(show = FALSE)
  ),

  defaultColDef = colDef(vAlign = "center"),
  defaultPageSize = 6
)
```
