---
editor: visual
---

```{r}
#| include: false
source("setup.R")
```

```{r}

#G1 Marital Status
#Create new data frame to drop "group forums only" (unsure of what that means), combine redundant categories
maritaldf <- stupiddf3 %>%
  mutate(MaritalStatus_clean = case_when(
    MaritalStatus == "Single, Divorced" ~ "Divorced",
    MaritalStatus == "Single, Separated" ~ "Separated",
    MaritalStatus == "Single, Widowed" ~ "Widowed",
    MaritalStatus == "Divorced" ~ "Divorced",
    MaritalStatus == "Separated" ~ "Separated",
    MaritalStatus == "Widowed" ~ "Widowed",
    MaritalStatus == "Single" ~ "Single",
    MaritalStatus == "Engaged" ~ "Engaged",
    MaritalStatus == "In Relationship" ~ "In Relationship",
    MaritalStatus == "Married" ~ "Married",
    MaritalStatus == "Groups Forums Only" ~ "Groups Forums Only"
  )) %>%
  filter(MaritalStatus_clean != "Groups Forums Only")

maritaldf_plot <- maritaldf %>%
  count(MaritalStatus_clean) %>%
  mutate(
    percent = n / sum(n) * 100
  )

maritaldf_plot <- ggplot(
  maritaldf_plot,
  aes(
    x = reorder(MaritalStatus_clean, percent),
    y = percent,
    fill = MaritalStatus_clean
  )
) +
  geom_col(width = 0.7, show.legend = FALSE) +
  geom_text(
    aes(label = sprintf("%.1f%%", percent)),
    hjust = -0.15,
    size = 3
  ) +
  coord_flip() +
  scale_y_continuous(
    labels = function(x) paste0(x, "%"),
    expand = expansion(mult = c(0, 0.20))
  ) +
  scale_fill_manual(values = my_palette) +
  labs(
    title = "Marital Status of Users",
    x = NULL,
    y = "Percent"
  ) +
  theme_site() +
  theme(
    plot.margin = margin(10, 20, 10, 10)
  )

# Looking For 
#create new data frame, replace "NA" values w "No Response", drop "Groups and forums activity"

lookingfordf <- stupiddf3 %>%
  mutate(LookingFor = tidyr::replace_na(LookingFor, "No Response")) %>%
  filter(LookingFor != "Groups and forums activity") %>%
  dplyr::count(LookingFor) %>%
  mutate(
    percent = n / sum(n) * 100,
    LookingFor = forcats::fct_reorder(LookingFor, percent)
  ) %>%
  arrange(percent)

lookingfordf_plot <- ggplot(
  lookingfordf,
  aes(
    x = LookingFor,
    y = percent,
    fill = LookingFor
  )
) +
  geom_col(width = 0.72, show.legend = FALSE) +
  geom_text(
    aes(label = sprintf("%.1f%%", percent)),
    hjust = -0.15,
    size = 3
  ) +
  coord_flip() +
  scale_y_continuous(
    labels = function(x) paste0(x, "%"),
    expand = expansion(mult = c(0, 0.20))
  ) +
  scale_fill_manual(values = my_palette) +
  labs(
    title = "What Are Users Looking For?",
    x = NULL,
    y = "Percent"
  ) +
  theme_site() +
  theme(
    plot.margin = margin(10, 20, 10, 10)
  )

#G3 Wants Kids
#drop n/a values from chart, regroup 
wantkiddf <- stupiddf3 %>%
  dplyr::count(WantChildren)
wantkiddf$WantChildren[is.na(wantkiddf$WantChildren)] <- "No Response"

wantkiddf <- stupiddf3 %>%
  mutate(WantChildren_clean = case_when(
    WantChildren == "Cannot have children" ~ "Do not wish to procreate",
    WantChildren == "Do not wish to procreate" ~ "Do not wish to procreate",
    WantChildren == "Do not wish to procreate (further)" ~ "Do not wish to procreate",
    WantChildren == "I have one child" ~ "Has Children",
    WantChildren == "I have three children" ~ "Has Children",
    WantChildren == "I have two children" ~ "Has Children",
    WantChildren == "Not yet but would like to" ~ "Would like to have children",
    WantChildren == "Prefer not to say" ~ "No Response",
    WantChildren == "Undecided" ~ "Undecided",
    WantChildren == "Would like to have 1 child" ~ "Would like to have children",
    WantChildren == "Would like to have 2 children" ~ "Would like to have children",
    WantChildren == "Would like to have 3 children" ~ "Would like to have children",
    WantChildren == "Would like to have 4 children" ~ "Would like to have children",
    WantChildren == "Would like to have children" ~ "Would like to have children",
    WantChildren == "Would like to have more than 4" ~ "Would like to have children",
    WantChildren == "No Response" ~ "No Response",
  )) %>%
  filter(WantChildren_clean !="No Response")

wantkiddf_plot <- wantkiddf %>%
  count(WantChildren_clean) %>%
  mutate(
    percent = n / sum(n) * 100
  )

wantkiddf_plot <- ggplot(
  wantkiddf_plot,
  aes(
    x = WantChildren_clean,
    y = percent,
    fill = WantChildren_clean
  )
) +
  geom_col(width = 0.7, show.legend = FALSE) +
  geom_text(
    aes(label = sprintf("%.1f%%", percent)),
    hjust = -0.15,
    size = 3
  ) +
  coord_flip() +
  scale_y_continuous(
    labels = function(x) paste0(x, "%"),
    expand = expansion(mult = c(0, 0.20))
  ) +
  scale_fill_manual(values = my_palette) +
  labs(
    title = "Do Users Want Children?",
    subtitle = "Grouped responses (excluding N/A)",
    x = NULL,
    y = NULL
  ) +
  theme_site() +
  theme(
    plot.margin = margin(10, 20, 10, 10)
  )

#G4 Has Kids

havekiddf <- stupiddf3 %>%
  mutate(HaveChildren = tidyr::replace_na(HaveChildren, "No Response")) %>%
  dplyr::count(HaveChildren) %>%
  mutate(percent = n / sum(n) * 100)

havekiddf_plot <- ggplot(
  havekiddf,
  aes(
    x = HaveChildren,
    y = percent,
    fill = HaveChildren
  )
) +
  geom_col(width = 0.7, show.legend = FALSE) +
  geom_text(
    aes(label = sprintf("%.1f%%", percent)),
    hjust = -0.15,
    size = 3
  ) +
  coord_flip() +
  scale_y_continuous(
    labels = function(x) paste0(x, "%"),
    expand = expansion(mult = c(0, 0.20))
  ) +
  scale_fill_manual(values = my_palette) +
  labs(
    title = "Do Users Have Children?",
    x = NULL,
    y = NULL
  ) +
  theme_site() +
  theme(
    plot.margin = margin(10, 20, 10, 10)
  )
  
```

::: {layout-ncol=2}

```{r}
#| fig-width: 5.5
#| fig-height: 4.25
#| out-width: "100%"
maritaldf_plot
```

```{r}
#| fig-width: 5.5
#| fig-height: 4.25
#| out-width: "100%"
lookingfordf_plot
```

```{r}
#| fig-width: 5.5
#| fig-height: 4.25
#| out-width: "100%"
wantkiddf_plot
```

```{r}
#| fig-width: 5.5
#| fig-height: 4.25
#| out-width: "100%"
havekiddf_plot
```

:::